sylius_admin_dashboard:
    path: /
    defaults:
        _controller: sylius.controller.admin.dashboard:indexAction

sylius_admin_user:
    resource: "@ToroAdminBundle/Resources/config/routing/admin_user.yml"

sylius_admin_security:
    resource: "@ToroAdminBundle/Resources/config/routing/security.yml"

sylius_admin_page:
    resource: "@ToroAdminBundle/Resources/config/routing/page.yml"

sylius_admin_post:
    resource: "@ToroAdminBundle/Resources/config/routing/post.yml"

sylius_admin_country:
    resource: "@ToroAdminBundle/Resources/config/routing/country.yml"

sylius_admin_province:
    resource: "@ToroAdminBundle/Resources/config/routing/province.yml"
