sylius_admin_dashboard:
    path: /
    defaults:
        _controller: sylius.controller.admin.dashboard:indexAction

sylius_admin_security:
    resource: "@ToroAdminBundle/Resources/config/routing/security.yml"

sylius_admin_page:
    resource: "@ToroAdminBundle/Resources/config/routing/page.yml"
