sylius_grid:
    grids:
        sylius_admin_user:
            driver:
                name: doctrine/orm
                options:
                    class: %sylius.model.admin_user.class%
                    repository:
                        method: createNoneRootQueryBuilder
            sorting:
                firstName: asc
                lastName: asc
                email: asc
            fields:
                firstName:
                    type: string
                    label: "First Name"
                    sortable: ~
                lastName:
                    type: string
                    label: "Last Name"
                    sortable: ~
                email:
                    type: string
                    label: "Email"
                    sortable: ~
                created_at:
                    type: datetime
                    label: "Created Date"
                    options:
                        format: d-m-Y H:i
                enabled:
                    type: twig
                    label: toro.ui.enabled
                    options:
                        template: "@ToroAdmin/Grid/Field/yesNo.html.twig"
            filters:
                name:
                    type: string
                    label: Name or Email
                    options:
                        default: true
                        fields:
                            - firstName
                            - lastName
                            - email
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
