sylius_grid:
    grids:
        sylius_admin_channel:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.channel.class%"
            sorting:
                nameAndDescription: asc
            fields:
                code:
                    type: twig
                    label: Code
                    path: .
                    options:
                        template: ToroAdminBundle:Channel/Field:code.html.twig
                nameAndDescription:
                    type: twig
                    label: Name
                    path: .
                    sortable: name
                    options:
                        template: ToroAdminBundle:Grid/Field:nameAndDescription.html.twig
                themeName:
                    type: string
                    label: Theme
                enabled:
                    type: twig
                    label: Enabled
                    options:
                        template: ToroAdminBundle:Grid/Field:enabled.html.twig
            filters:
                code:
                    type: string
                    label: Code
                name:
                    type: string
                    label: Name
                enabled:
                    type: boolean
                    label: Enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
