sylius_grid:
    grids:
        sylius_admin_customer:
            driver:
                name: doctrine/orm
                options:
                    class: %sylius.model.customer.class%
            sorting:
                firstName: asc
                lastName: asc
                email: asc
            fields:
                firstName:
                    type: string
                    label: "First Name"
                    sortable: ~
                lastName:
                    type: string
                    label: "Last Name"
                    sortable: ~
                email:
                    type: string
                    label: "Email"
                    sortable: ~
                createdAt:
                    type: datetime
                    label: Create at
                    sortable: ~
                    options:
                        format: d-m-Y H:i
                confirmed:
                    type: twig
                    label: Confirmed
                    path: .
                    options:
                        template: ToroAdminBundle:Customer/Field:confirmed.html.twig
            filters:
                name:
                    type: string
                    label: Name or Email
                    options:
                        default: true
                        fields:
                            - translation.firstName
                            - translation.lastName
                            - email
                confirmed:
                    type: boolean
                    label: Confirmed
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
