sylius_grid:
    grids:
        sylius_admin_locale:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.locale.class%"
            sorting:
                code: asc
            fields:
                code:
                    type: string
                    label: Code
                    sortable: ~
                name:
                    type: twig
                    label: Name
                    path: .
                    options:
                        template: ToroAdminBundle:Locale/Field:name.html.twig
                enabled:
                    type: twig
                    label: Enabled
                    options:
                        template: ToroAdminBundle:Grid/Field:enabled.html.twig
            filters:
                code:
                    type: string
                    label: Code
                enabled:
                    type: boolean
                    label: Enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
