sylius_grid:
    grids:
        sylius_admin_province:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.province.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: [ "%locale%" ]
            filters:
                name:
                    type: string
                    label: Name
                    options:
                        default: true
                        fields:
                            - translation.name
                            - translation.abbreviation
            sorting:
                code: asc
            fields:
                code:
                    type: string
                    label: Code
                    sortable: ~
                name:
                    type: string
                    label: Name
                    sortable: translation.name
                abbreviation:
                    type: string
                    label: Abbreviation
                    sortable: translation.abbreviation
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
