sylius_grid:
    grids:
        sylius_admin_taxon:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.taxon.class%"
                    repository:
                        method: createFilterQueryBuilder
                        arguments: [ "%locale%", $code ]
            limits: [1000]
            fields:
                name:
                    type: twig
                    label: Name
                    path: .
                    options:
                        template: "@ToroAdmin/Taxon/Grid/Field/taxonLevel.html.twig"
                code:
                    type: string
                    label: Code
                slug:
                    type: string
                    label: Slug
            actions:
                main:
                    index:
                        type: link
                        label: Roots
                        options:
                            icon: 'fa fa-chevron-left'
                            class: 'btn btn-lg btn-default btn-taxon-root-back'
                            route: sylius_admin_taxon_index
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
