#jms_serializer:
#    metadata:
#        directories:
#            sylius-core:
#                namespace_prefix: "Sylius\\Component\\Core"
#                path: "@SyliusCoreBundle/Resources/config/serializer"
