imports:
    - { resource: "@ToroAdminBundle/Resources/config/app/parameters.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/doctrine_cache.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/doctrine.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/twig.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/fos_rest.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/jms_serializer.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/liip_imagine.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/stof_doctrine_extensions.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/sylius_channel.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/sylius_locale.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/sylius_mailer.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/sylius_resource.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/sylius_user.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/sylius_grid.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/sylius_fixtures.yml" }
    - { resource: "@ToroAdminBundle/Resources/config/app/sylius_taxonomy.yml" }
