sylius_addressing:
    resources:
        province:
            classes:
                model: Toro\Bundle\AdminBundle\Model\Province
                repository: Toro\Bundle\AdminBundle\Doctrine\ORM\ProvinceRepository
                form: Toro\Bundle\AdminBundle\Form\Type\ProvinceType
        country:
            classes:
                model: Toro\Bundle\AdminBundle\Model\Country
        zone:
            classes:
                model: Toro\Bundle\AdminBundle\Model\Zone
        zone_member:
            classes:
                model: Toro\Bundle\AdminBundle\Model\ZoneMember

sylius_resource:
    resources:
        sylius.province_translation:
            driver: doctrine/orm
            classes:
                model: Toro\Bundle\AdminBundle\Model\ProvinceTranslation
                interface: Toro\Bundle\AdminBundle\Model\ProvinceTranslationInterface
                form: Toro\Bundle\AdminBundle\Form\Type\ProvinceTranslationType
