sylius_locale:
    resources:
        locale:
            classes:
                model: Toro\Bundle\AdminBundle\Model\Locale
                controller: Toro\Bundle\AdminBundle\Sylius\Controller\LocaleController
