sylius_resource:
    resources:
        toro.menu:
            driver: doctrine/orm
            classes:
                model: Toro\Bundle\AdminBundle\Model\Menu
                interface: Toro\Bundle\AdminBundle\Model\MenuInterface
                repository: Toro\Bundle\AdminBundle\Doctrine\ORM\MenuRepository
                form: Toro\Bundle\AdminBundle\Form\Type\MenuType
            translation:
                classes:
                    model: Toro\Bundle\AdminBundle\Model\MenuTranslation
                    interface: Toro\Bundle\AdminBundle\Model\MenuTranslationInterface
                    form: Toro\Bundle\AdminBundle\Form\Type\MenuTranslationType
