sylius_addressing:
    resources:
        province:
            classes:
                model: Toro\Bundle\AdminBundle\Model\Province
                repository: Toro\Bundle\AdminBundle\Doctrine\ORM\ProvinceRepository
                form:
                    default: Toro\Bundle\AdminBundle\Form\Type\ProvinceType
            validation_groups:
                default:
                    - toro
        country:
            classes:
                model: Toro\Bundle\AdminBundle\Model\Country
                form:
                    default: Toro\Bundle\AdminBundle\Form\Type\CountryType
        zone:
            classes:
                model: Toro\Bundle\AdminBundle\Model\Zone
        zone_member:
            classes:
                model: Toro\Bundle\AdminBundle\Model\ZoneMember

sylius_resource:
    resources:
        sylius.province_translation:
            driver: doctrine/orm
            classes:
                model: Toro\Bundle\AdminBundle\Model\ProvinceTranslation
                interface: Toro\Bundle\AdminBundle\Model\ProvinceTranslationInterface
                form:
                    default: Toro\Bundle\AdminBundle\Form\Type\ProvinceTranslationType
            validation_groups:
                default:
                    - toro
