sylius_resource:
    translation:
        locale_provider: sylius.locale_provider.admin

    resources:
        toro.menu:
            driver: doctrine/orm
            classes:
                model: Toro\Bundle\AdminBundle\Model\Menu
                interface: Toro\Bundle\AdminBundle\Model\MenuInterface
                repository: Toro\Bundle\AdminBundle\Doctrine\ORM\MenuRepository
                form:
                    default: Toro\Bundle\AdminBundle\Form\Type\MenuType
            translation:
                classes:
                    model: Toro\Bundle\AdminBundle\Model\MenuTranslation
                    interface: Toro\Bundle\AdminBundle\Model\MenuTranslationInterface
                    form:
                        default: Toro\Bundle\AdminBundle\Form\Type\MenuTranslationType
                validation_groups:
                    default:
                        - toro
            validation_groups:
                default:
                    - toro
