sylius_mailer:
    resources:
        email:
            classes:
                model: Toro\Bundle\AdminBundle\Model\Email
    sender:
        name: Example.com
        address: no-reply@example.com
    templates:
        sylius.email.order_confirmation.name: "SyliusCoreBundle:Email:orderConfirmation.html.twig"
        sylius.email.order_comment.name: "SyliusCoreBundle:Email:orderComment.html.twig"
        sylius.email.shipment_confirmation.name: "SyliusCoreBundle:Email:shipmentConfirmation.html.twig"
        sylius.email.user_confirmation.name: "SyliusCoreBundle:Email:userConfirmation.html.twig"
        sylius.email.password_reset.name: "SyliusCoreBundle:Email:passwordReset.html.twig"
    emails:
        order_confirmation:
            subject: sylius.emails.order_confirmation.subject
            template: "SyliusCoreBundle:Email:orderConfirmation.html.twig"
        order_comment:
            subject: sylius.emails.order_comment.subject
            template: "SyliusCoreBundle:Email:orderComment.html.twig"
        shipment_confirmation:
            subject: sylius.emails.shipment_confirmation.subject
            template: "SyliusCoreBundle:Email:shipmentConfirmation.html.twig"
        user_confirmation:
            subject: sylius.emails.user_confirmation.subject
            template: "SyliusCoreBundle:Email:userConfirmation.html.twig"
        password_reset:
            subject: sylius.emails.user.password_reset.subject
            template: "SyliusCoreBundle:Email:passwordReset.html.twig"
        reset_password_token:
            subject: sylius.emails.user.password_reset.subject
            template: "SyliusCoreBundle:Email:passwordReset.html.twig"
        reset_password_pin:
            subject: sylius.emails.user.password_reset.subject
            template: "SyliusCoreBundle:Email:passwordReset.html.twig"
