sylius_user:
    resources:
        admin:
            user:
                classes:
                    model: Toro\Bundle\AdminBundle\Model\AdminUser
                    interface: Toro\Bundle\AdminBundle\Model\AdminUserInterface
                    repository: Toro\Bundle\AdminBundle\Doctrine\ORM\AdminUserRepository
                    form: Toro\Bundle\AdminBundle\Form\Type\AdminUserType
