twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        cx_chanel: "@sylius.context.channel"
        channel_context: "@sylius.context.channel" # @deprecated
        current_locale: "%locale%"
        branding:
            name: Inthriy
            copyright: 2016 Inthriy Admin
