sylius_admin_locale:
    resource: |
        alias: sylius.locale
        section: admin
        templates: ToroAdminBundle:Crud
        except: ['show', 'delete']
        redirect: index
        grid: sylius_admin_locale
        vars:
            all:
                subheader: toro.ui.manage_languages_available_in_the_store
                templates:
                    form: ToroAdminBundle:Locale:_form.html.twig
            index:
                icon: translate
    type: sylius.resource
