toro_admin_cms_page:
    resource: |
        alias: toro.page
        section: admin
        templates: ToroAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: toro_admin_page
        permission: true
        vars:
          create:
            templates:
                form: "@ToroAdmin/Page/_form_bs4_create.html.twig"
          update:
            templates:
                form: "@ToroAdmin/Page/_form_bs4.html.twig"
          index:
            icon: ti-book
    type: sylius.resource
