toro_admin_cms_post:
    resource: |
        alias: toro.post
        section: admin
        templates: ToroAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: toro_admin_post
        vars:
          create:
            templates:
                form: "@ToroAdmin/Post/_form_bs4_create.html.twig"
          update:
            templates:
                form: "@ToroAdmin/Post/_form_bs4.html.twig"
          index:
            icon: ti-book
    type: sylius.resource
