sylius_admin_province:
    resource: |
        alias: sylius.province
        section: admin
        templates: ToroAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: sylius_admin_province
        vars:
            all:
                templates:
                    form: ToroAdminBundle:Province:_form.html.twig
            index:
                icon: flag
    type: sylius.resource
