sylius_admin_channel:
    resource: "@ToroAdminBundle/Resources/config/routing/channel.yml"

sylius_admin_locale:
    resource: "@ToroAdminBundle/Resources/config/routing/locale.yml"

sylius_admin_menu:
    resource: "@ToroAdminBundle/Resources/config/routing/menu.yml"
