sylius_admin_taxon:
    resource: |
        alias: sylius.taxon
        section: admin
        templates: ToroAdminBundle:Crud
        except: ['show', 'index']
        redirect: update
        form: Toro\Bundle\CmsBundle\Form\Type\TaxonType
        vars:
            all:
                subheader: toro.ui.manage_categorization_of_your_products
                templates:
                    form: ToroAdminBundle:Taxon:_form.html.twig
    type: sylius.resource

sylius_admin_taxon_index:
    path: /taxons/
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Template:template
        template: ToroAdminBundle:Taxon:index.html.twig

sylius_admin_taxon_index_create:
    path: /taxons/create
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:createAction
        _sylius:
            template: ToroAdminBundle:Taxon:_formIndex.html.twig
            form: Toro\Bundle\CmsBundle\Form\Type\TaxonType

sylius_admin_taxon_roots:
    path: /taxons/roots
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            template: ToroAdminBundle:Taxon:_roots.html.twig
            repository:
                method: findRootNodes

sylius_admin_taxon_children:
    path: /taxons/children/{code}
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            template: ToroAdminBundle:Taxon:_children.html.twig
            repository:
                method: findChildren
                arguments: [$code, "%locale%"]

sylius_admin_taxon_show_bycode:
    path: /taxons/show/{code}
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:showAction
        _sylius:
            template: $template
            repository:
                method: findOneByCode
                arguments: [$code]
